config/routes.rb
CarListing::Application.routes.draw do

  resources :cars

  root 'cars#index'

end

app/models/car.rb
class Car < ActiveRecord::Base
  validates_presence_of :color, :year, :mileage
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController

  def create
    @car = Car.new(params.require(:car).permit(:color, :year, :mileage, :description))
    if @car.save
      redirect_to @car, notice: 'Listing successfully created.'
    else
      render action: 'new'
    end
  end

  def index
    @cars = Car.all
  end

  def new
    @car = Car.new
    @options = DateTime.now.year.downto(1980).to_a
    @options.unshift(nil)
  end

  def show
    @car = Car.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cars/index.html.erb
<h1>Car Listing Index</h1>
<%= link_to 'New Listing', new_car_path %>
<% @cars.each do |car| %>
</p><%= link_to car.id, car %>. <%= car.color + ' ' + car.year %></p>
<% end %>

app/views/cars/new.html.erb
<h1>New Car Listing</h1>

<%= form_for(@car) do |f| %>
  <% if @car.errors.any? %>
    <p>Error(s) detected; inquiry not saved.</p>
  <% end %>
    <div>
      <%= f.label :color %>:
      <%= f.text_field :color %>
    </div>
    <div>
      <%= f.label :year %>:
      <%= f.select :year, @options %>
    </div>
    <div>
      <%= f.label :mileage %>:
      <%= f.text_area :mileage %>
    </div>
    <div>
      <%= f.label :description %>:
      <%= f.text_field :description %>
    </div>
    <div>
      <%= f.submit "List Car" %>
    </div>
<% end %>

app/views/cars/show.html.erb
<h1>Listing #<%= @car.id %></h1>
<p id="notice"><%= notice %></p>
<table>
  <tr>
    <th>Color</th>
    <th>Year</th>
    <th>Mileage</th>
    <th>Description</th>
  </tr>
  <tr>
    <td><%= @car.color %></td>
    <td><%= @car.year %></td>
    <td><%= @car.mileage %></td>
    <td><%= @car.description %></td>
  </tr>
</table>
<%= link_to 'Car Listing Index', cars_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CarListing</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>